version: 2.1

jobs:
  build:
    docker:
      - image: node:16
    working_directory: ~/hieudoan.news
    steps:
      - checkout
      - run:
          name: 'Installing YARN packages'
          command: yarn install
      - run:
          name: 'Run YARN build'
          command: yarn build
      - run:
          name: 'Check files and folder'
          command: pwd && ls -la
      - store_artifacts:
          path: ./dist
          destination: build
  test:
    docker:
      - image: node:16
    working_directory: ~/hieudoan.news
    steps:
      - checkout
      - run:
          name: 'Installing YARN packages'
          command: yarn install
      - run:
          name: 'Run YARN tests'
          command: yarn test
      - run:
          name: 'Check files and folder'
          command: pwd && ls -la
      - store_test_results:
          path: ./coverage

workflows:
  version: 2
  build_test:
    jobs:
      - build
      - test:
          requires:
            - build
